name: Docker Image CI

on:
  push:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: reg.wintern.at
          username: ${{ secrets.DOCKER_REG_USER }}
          password: ${{ secrets.DOCKER_REG_PW }}

      - name: Build Image
        run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=bucketlist

      - name: List Images
        run: docker images

      - name: Push to repo
        run: docker push reg.wintern.at/bucketlist:latest